/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Swing;

import Model.City;
import Services.Delete;
import Services.Lista;
import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author Aluno
 */
public class Deletar extends javax.swing.JFrame {

    /**
     * Creates new form Delete
     */
    private int id;
    private Lista lista;
    private City cidade;
    
    public Deletar(int id) {  
        initComponents();
        this.id = id;
        setTitle("Deletar");
        //Delete delete = new Delete();
        this.lista = new Lista();
        this.cidade = lista.getCidades().get(id);
        idCitySelect.setText(cidade.getMunicipio());
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(Deletar.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttomYesDelCity = new javax.swing.JButton();
        buttonNoDelCity = new javax.swing.JButton();
        idCitySelect = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Alert");

        jLabel3.setText("Deseja deletar a cidade selecionada?");

        buttomYesDelCity.setText("Sim");
        buttomYesDelCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttomYesDelCityActionPerformed(evt);
            }
        });

        buttonNoDelCity.setText("Não");
        buttonNoDelCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNoDelCityActionPerformed(evt);
            }
        });

        idCitySelect.setText("City");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(idCitySelect)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttomYesDelCity)
                        .addGap(18, 18, 18)
                        .addComponent(buttonNoDelCity))
                    .addComponent(jLabel2))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(idCitySelect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttomYesDelCity)
                    .addComponent(buttonNoDelCity))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttomYesDelCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttomYesDelCityActionPerformed

        Delete delete = new Delete();
        
        lista.atualizarLista();
        City cidade = lista.getCidades().get(id);  
        delete.DeleteById(id, lista);
        
        
        
        dispose();
        
        
    }//GEN-LAST:event_buttomYesDelCityActionPerformed

    
    private void buttonNoDelCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNoDelCityActionPerformed
        dispose();
    }//GEN-LAST:event_buttonNoDelCityActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttomYesDelCity;
    private javax.swing.JButton buttonNoDelCity;
    private javax.swing.JLabel idCitySelect;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
